/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derstakip;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ali Mert
 */
public class Program extends javax.swing.JFrame {
    
    

    
    
    
Ders1 d = new Ders1();

public void kayitli_konulari_goster() throws SQLException{
        kayitliKonularListesi.setModel(new DefaultListModel());
        DefaultListModel model = (DefaultListModel)kayitliKonularListesi.getModel();
        model.removeAllElements();
        String[] konular = d.Konu_Goster();
        model = (DefaultListModel)kayitliKonularListesi.getModel();
        for (int i = 0; i < konular.length; i++) {
            model.addElement(konular[i]);

        }
}
    /**
     * Creates new form Program
     */
    public Program() throws SQLException {
        initComponents();
  
        toplamderssaati.setText(String.valueOf(d.ders_saat_toplami()));
        ortalamaderssaati.setText(String.valueOf(d.ders_saat_ortalama()));
        sayisalderssayisi.setText(String.valueOf(d.sayisal_sayisi()));
        sozelderssayisi.setText(String.valueOf(d.sozel_sayisi()));
        
        
        
        dersEkleP.setVisible(false);
        dersGoruntuleP.setVisible(false);
        dersKonusuP.setVisible(false);
        dersSecP.setVisible(false);
        kayitliKonularListesi.setVisible(false);
        jScrollPane2.setVisible(false);

        
        this.getContentPane().setPreferredSize(new java.awt.Dimension(640, 480));
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        kayitliKonularListesi = new javax.swing.JList<>();
        dersKonusuP = new javax.swing.JPanel();
        dersAdiBaslik3 = new javax.swing.JLabel();
        dersKonusuEkle = new javax.swing.JButton();
        dersKonusuBaslik1 = new javax.swing.JLabel();
        dersKonusuEkleDersAdi = new javax.swing.JTextField();
        dersKonusuEkleDersKonusu = new javax.swing.JTextField();
        dersGoruntuleP = new javax.swing.JPanel();
        dersAdiBaslik2 = new javax.swing.JLabel();
        dersGoruntuleDersAdi = new javax.swing.JTextField();
        dersGoruntule = new javax.swing.JButton();
        dersEkleP = new javax.swing.JPanel();
        dersSecP = new javax.swing.JPanel();
        say = new javax.swing.JButton();
        soz = new javax.swing.JButton();
        dersAdiBaslik1 = new javax.swing.JLabel();
        dersEkleDersAdi = new javax.swing.JTextField();
        dersTuruBaslik1 = new javax.swing.JLabel();
        dersTuru = new javax.swing.JLabel();
        dersTuruSec = new javax.swing.JButton();
        dersSaatiBaslik1 = new javax.swing.JLabel();
        dersSaati = new javax.swing.JTextField();
        dersEkle = new javax.swing.JButton();
        navigasyon = new javax.swing.JPanel();
        dersKonusuEkleNav = new javax.swing.JButton();
        dersGoruntuleNav = new javax.swing.JButton();
        dersEkleNav = new javax.swing.JButton();
        menuleriKapat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        toplamderssaati = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ortalamaderssaati = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sayisalderssayisi = new javax.swing.JLabel();
        sozelderssayisi = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ders Takip");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/derstakip/kaynak/simge.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);

        kayitliKonularListesi.setBackground(new java.awt.Color(34, 42, 52));
        kayitliKonularListesi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 42, 52), 5));
        kayitliKonularListesi.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        kayitliKonularListesi.setForeground(new java.awt.Color(53, 120, 153));
        kayitliKonularListesi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ders1", "Ders2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        kayitliKonularListesi.setOpaque(false);
        jScrollPane2.setViewportView(kayitliKonularListesi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, 120));

        dersKonusuP.setBackground(new java.awt.Color(34, 42, 52));
        dersKonusuP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dersAdiBaslik3.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        dersAdiBaslik3.setForeground(new java.awt.Color(103, 90, 166));
        dersAdiBaslik3.setText("DERS ADI");
        dersKonusuP.add(dersAdiBaslik3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 10));

        dersKonusuEkle.setBackground(new java.awt.Color(29, 38, 50));
        dersKonusuEkle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersKonusuEkle.setForeground(new java.awt.Color(103, 90, 166));
        dersKonusuEkle.setText("EKLE");
        dersKonusuEkle.setBorder(null);
        dersKonusuEkle.setContentAreaFilled(false);
        dersKonusuEkle.setOpaque(true);
        dersKonusuEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersKonusuEkleActionPerformed(evt);
            }
        });
        dersKonusuP.add(dersKonusuEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, 20));

        dersKonusuBaslik1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        dersKonusuBaslik1.setForeground(new java.awt.Color(103, 90, 166));
        dersKonusuBaslik1.setText("DERS KONUSU");
        dersKonusuP.add(dersKonusuBaslik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 10));

        dersKonusuEkleDersAdi.setBackground(new java.awt.Color(39, 48, 60));
        dersKonusuEkleDersAdi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersKonusuEkleDersAdi.setForeground(new java.awt.Color(180, 180, 180));
        dersKonusuEkleDersAdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 48, 60), 2));
        dersKonusuP.add(dersKonusuEkleDersAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        dersKonusuEkleDersKonusu.setBackground(new java.awt.Color(39, 48, 60));
        dersKonusuEkleDersKonusu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersKonusuEkleDersKonusu.setForeground(new java.awt.Color(180, 180, 180));
        dersKonusuEkleDersKonusu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 48, 60), 2));
        dersKonusuP.add(dersKonusuEkleDersKonusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 20));

        getContentPane().add(dersKonusuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 190, 120));

        dersGoruntuleP.setBackground(new java.awt.Color(34, 42, 52));
        dersGoruntuleP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dersAdiBaslik2.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        dersAdiBaslik2.setForeground(new java.awt.Color(53, 120, 153));
        dersAdiBaslik2.setText("DERS ADI");
        dersGoruntuleP.add(dersAdiBaslik2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 10));

        dersGoruntuleDersAdi.setBackground(new java.awt.Color(39, 48, 60));
        dersGoruntuleDersAdi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersGoruntuleDersAdi.setForeground(new java.awt.Color(180, 180, 180));
        dersGoruntuleDersAdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 48, 60), 2));
        dersGoruntuleP.add(dersGoruntuleDersAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        dersGoruntule.setBackground(new java.awt.Color(29, 38, 50));
        dersGoruntule.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersGoruntule.setForeground(new java.awt.Color(53, 120, 153));
        dersGoruntule.setText("GÖRÜNTÜLE");
        dersGoruntule.setBorder(null);
        dersGoruntule.setContentAreaFilled(false);
        dersGoruntule.setOpaque(true);
        dersGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersGoruntuleActionPerformed(evt);
            }
        });
        dersGoruntuleP.add(dersGoruntule, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, 20));

        getContentPane().add(dersGoruntuleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, 80));

        dersEkleP.setBackground(new java.awt.Color(34, 42, 52));
        dersEkleP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dersSecP.setOpaque(false);
        dersSecP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        say.setBackground(new java.awt.Color(29, 38, 50));
        say.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        say.setForeground(new java.awt.Color(122, 76, 140));
        say.setText("SAY");
        say.setBorder(null);
        say.setContentAreaFilled(false);
        say.setOpaque(true);
        say.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sayActionPerformed(evt);
            }
        });
        dersSecP.add(say, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        soz.setBackground(new java.awt.Color(29, 38, 50));
        soz.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        soz.setForeground(new java.awt.Color(122, 76, 140));
        soz.setText("SÖZ");
        soz.setBorder(null);
        soz.setContentAreaFilled(false);
        soz.setOpaque(true);
        soz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sozActionPerformed(evt);
            }
        });
        dersSecP.add(soz, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 20));

        dersEkleP.add(dersSecP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 20));

        dersAdiBaslik1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        dersAdiBaslik1.setForeground(new java.awt.Color(122, 76, 140));
        dersAdiBaslik1.setText("DERS ADI");
        dersEkleP.add(dersAdiBaslik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 10));

        dersEkleDersAdi.setBackground(new java.awt.Color(39, 48, 60));
        dersEkleDersAdi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersEkleDersAdi.setForeground(new java.awt.Color(180, 180, 180));
        dersEkleDersAdi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 48, 60), 2));
        dersEkleDersAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersEkleDersAdiActionPerformed(evt);
            }
        });
        dersEkleP.add(dersEkleDersAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 20));

        dersTuruBaslik1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        dersTuruBaslik1.setForeground(new java.awt.Color(122, 76, 140));
        dersTuruBaslik1.setText("DERS TÜRÜ");
        dersEkleP.add(dersTuruBaslik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 10));

        dersTuru.setBackground(new java.awt.Color(39, 48, 60));
        dersTuru.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersTuru.setForeground(new java.awt.Color(180, 180, 180));
        dersTuru.setText("SAY");
        dersTuru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 48, 60), 2));
        dersTuru.setOpaque(true);
        dersEkleP.add(dersTuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 20));

        dersTuruSec.setBackground(new java.awt.Color(29, 38, 50));
        dersTuruSec.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dersTuruSec.setForeground(new java.awt.Color(122, 76, 140));
        dersTuruSec.setText("...");
        dersTuruSec.setBorder(null);
        dersTuruSec.setContentAreaFilled(false);
        dersTuruSec.setOpaque(true);
        dersTuruSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersTuruSecActionPerformed(evt);
            }
        });
        dersEkleP.add(dersTuruSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 40, 20));

        dersSaatiBaslik1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        dersSaatiBaslik1.setForeground(new java.awt.Color(122, 76, 140));
        dersSaatiBaslik1.setText("DERS SAATİ");
        dersEkleP.add(dersSaatiBaslik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 10));

        dersSaati.setBackground(new java.awt.Color(39, 48, 60));
        dersSaati.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersSaati.setForeground(new java.awt.Color(180, 180, 180));
        dersSaati.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 48, 60), 2));
        dersSaati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersSaatiActionPerformed(evt);
            }
        });
        dersEkleP.add(dersSaati, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 20));

        dersEkle.setBackground(new java.awt.Color(29, 38, 50));
        dersEkle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dersEkle.setForeground(new java.awt.Color(122, 76, 140));
        dersEkle.setText("EKLE");
        dersEkle.setBorder(null);
        dersEkle.setContentAreaFilled(false);
        dersEkle.setOpaque(true);
        dersEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersEkleActionPerformed(evt);
            }
        });
        dersEkleP.add(dersEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 80, 20));

        getContentPane().add(dersEkleP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 160));

        navigasyon.setBackground(new java.awt.Color(42, 60, 78));
        navigasyon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dersKonusuEkleNav.setBackground(new java.awt.Color(39, 48, 60));
        dersKonusuEkleNav.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dersKonusuEkleNav.setForeground(new java.awt.Color(103, 90, 166));
        dersKonusuEkleNav.setText("Ders Konusu Ekle");
        dersKonusuEkleNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(103, 90, 166), 2));
        dersKonusuEkleNav.setContentAreaFilled(false);
        dersKonusuEkleNav.setOpaque(true);
        dersKonusuEkleNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersKonusuEkleNavActionPerformed(evt);
            }
        });
        navigasyon.add(dersKonusuEkleNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 190, 30));

        dersGoruntuleNav.setBackground(new java.awt.Color(39, 48, 60));
        dersGoruntuleNav.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dersGoruntuleNav.setForeground(new java.awt.Color(53, 120, 153));
        dersGoruntuleNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 120, 153), 2));
        dersGoruntuleNav.setContentAreaFilled(false);
        dersGoruntuleNav.setLabel("Ders Görüntüle");
        dersGoruntuleNav.setOpaque(true);
        dersGoruntuleNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersGoruntuleNavActionPerformed(evt);
            }
        });
        navigasyon.add(dersGoruntuleNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 190, 30));

        dersEkleNav.setBackground(new java.awt.Color(39, 48, 60));
        dersEkleNav.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dersEkleNav.setForeground(new java.awt.Color(122, 76, 140));
        dersEkleNav.setText("Ders Ekle");
        dersEkleNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 76, 140), 2));
        dersEkleNav.setContentAreaFilled(false);
        dersEkleNav.setOpaque(true);
        dersEkleNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dersEkleNavActionPerformed(evt);
            }
        });
        navigasyon.add(dersEkleNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 30));

        menuleriKapat.setBackground(new java.awt.Color(39, 48, 60));
        menuleriKapat.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        menuleriKapat.setForeground(new java.awt.Color(172, 56, 56));
        menuleriKapat.setText("X");
        menuleriKapat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 56, 56), 2));
        menuleriKapat.setContentAreaFilled(false);
        menuleriKapat.setOpaque(true);
        menuleriKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuleriKapatActionPerformed(evt);
            }
        });
        navigasyon.add(menuleriKapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 30));

        getContentPane().add(navigasyon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Toplam Ders Saati:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 20));

        toplamderssaati.setForeground(new java.awt.Color(255, 102, 102));
        toplamderssaati.setText("jLabel2");
        getContentPane().add(toplamderssaati, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 50, 20));

        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Ders Başına Ortalama Ders Saati:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        ortalamaderssaati.setForeground(new java.awt.Color(153, 255, 153));
        ortalamaderssaati.setText("jLabel3");
        getContentPane().add(ortalamaderssaati, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Sayısal Ders Sayısı:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 153, 255));
        jLabel4.setText("Sözel Ders Sayısı:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        sayisalderssayisi.setForeground(new java.awt.Color(102, 255, 255));
        sayisalderssayisi.setText("jLabel5");
        getContentPane().add(sayisalderssayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        sozelderssayisi.setForeground(new java.awt.Color(204, 153, 255));
        sozelderssayisi.setText("jLabel5");
        getContentPane().add(sozelderssayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/derstakip/kaynak/arkaplan.png"))); // NOI18N
        getContentPane().add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dersEkleNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersEkleNavActionPerformed
        // TODO add your handling code here:
        dersEkleP.setVisible(true);
        dersGoruntuleP.setVisible(false);
        dersKonusuP.setVisible(false);
        kayitliKonularListesi.setVisible(false);
    }//GEN-LAST:event_dersEkleNavActionPerformed

    private void dersGoruntuleNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersGoruntuleNavActionPerformed
        // TODO add your handling code here:
        dersEkleP.setVisible(false);
        dersGoruntuleP.setVisible(true);
        dersKonusuP.setVisible(false);
        kayitliKonularListesi.setVisible(false);
    }//GEN-LAST:event_dersGoruntuleNavActionPerformed

    private void dersKonusuEkleNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersKonusuEkleNavActionPerformed
        // TODO add your handling code here:
        dersEkleP.setVisible(false);
        dersGoruntuleP.setVisible(false);
        dersKonusuP.setVisible(true);
        kayitliKonularListesi.setVisible(false);
    }//GEN-LAST:event_dersKonusuEkleNavActionPerformed

    private void dersTuruSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersTuruSecActionPerformed
        // TODO add your handling code here:
        dersSecP.setVisible(true);
    }//GEN-LAST:event_dersTuruSecActionPerformed

    private void sayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sayActionPerformed
        // TODO add your handling code here:
        dersTuru.setText(say.getText());
        dersSecP.setVisible(false);
    }//GEN-LAST:event_sayActionPerformed

    private void sozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sozActionPerformed
        // TODO add your handling code here:
        dersTuru.setText(soz.getText());
        dersSecP.setVisible(false);
    }//GEN-LAST:event_sozActionPerformed

    private void dersEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersEkleActionPerformed
        // TODO add your handling code here:
        //dersTuru.setText(say.getText());
        dersSecP.setVisible(false);
        //dersEkleDersAdi.setText("");
        //dersSaati.setText("");
        String dersEkleDersAdi1 = dersEkleDersAdi.getText();
        String dersTuru1 = dersTuru.getText();
        int dersSaati1 = Integer.parseInt(dersSaati.getText());
        
    try {
        d.Ders_Ekle(dersEkleDersAdi1, dersTuru1, dersSaati1);
    } catch (SQLException ex) {
        Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }//GEN-LAST:event_dersEkleActionPerformed

    private void dersGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersGoruntuleActionPerformed
        // TODO add your handling code here:
        dersEkleP.setVisible(false);
        dersGoruntuleP.setVisible(false);
        dersKonusuP.setVisible(false);
        kayitliKonularListesi.setVisible(true);
        jScrollPane2.setVisible(true);

    try {
        kayitli_konulari_goster();
        
        //String dersGoruntuleDersAdi = dersGoruntuleDersAdi.getText();
    } catch (SQLException ex) {
        Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_dersGoruntuleActionPerformed

    private void dersKonusuEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersKonusuEkleActionPerformed
        // TODO add your handling code here:
       // dersKonusuEkleDersAdi.setText("");
       // dersKonusuEkleDersKonusu.setText("");
        
        
        String dersKonusuEkleDersAdi1 = dersKonusuEkleDersAdi.getText();
        String dersKonusuEkleDersKonusu1 = dersKonusuEkleDersKonusu.getText();
            System.out.println(dersKonusuEkleDersKonusu1);
    try {
        d.Konu_Ekle(dersKonusuEkleDersAdi1, dersKonusuEkleDersKonusu1);
    } catch (SQLException ex) {
        Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_dersKonusuEkleActionPerformed

    private void menuleriKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuleriKapatActionPerformed
        // TODO add your handling code here:
        dersEkleP.setVisible(false);
        dersGoruntuleP.setVisible(false);
        dersKonusuP.setVisible(false);
        kayitliKonularListesi.setVisible(false);
        dersSecP.setVisible(false);
        dersTuru.setText(say.getText());
        dersGoruntuleDersAdi.setText("");
        dersEkleDersAdi.setText("");
        dersSaati.setText("");
        dersKonusuEkleDersAdi.setText("");
        dersKonusuEkleDersAdi.setText("");
    }//GEN-LAST:event_menuleriKapatActionPerformed

    private void dersEkleDersAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersEkleDersAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dersEkleDersAdiActionPerformed

    private void dersSaatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dersSaatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dersSaatiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Program().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JLabel dersAdiBaslik1;
    private javax.swing.JLabel dersAdiBaslik2;
    private javax.swing.JLabel dersAdiBaslik3;
    private javax.swing.JButton dersEkle;
    private javax.swing.JTextField dersEkleDersAdi;
    private javax.swing.JButton dersEkleNav;
    private javax.swing.JPanel dersEkleP;
    private javax.swing.JButton dersGoruntule;
    private javax.swing.JTextField dersGoruntuleDersAdi;
    private javax.swing.JButton dersGoruntuleNav;
    private javax.swing.JPanel dersGoruntuleP;
    private javax.swing.JLabel dersKonusuBaslik1;
    private javax.swing.JButton dersKonusuEkle;
    private javax.swing.JTextField dersKonusuEkleDersAdi;
    private javax.swing.JTextField dersKonusuEkleDersKonusu;
    private javax.swing.JButton dersKonusuEkleNav;
    private javax.swing.JPanel dersKonusuP;
    private javax.swing.JTextField dersSaati;
    private javax.swing.JLabel dersSaatiBaslik1;
    private javax.swing.JPanel dersSecP;
    private javax.swing.JLabel dersTuru;
    private javax.swing.JLabel dersTuruBaslik1;
    private javax.swing.JButton dersTuruSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> kayitliKonularListesi;
    private javax.swing.JButton menuleriKapat;
    private javax.swing.JPanel navigasyon;
    private javax.swing.JLabel ortalamaderssaati;
    private javax.swing.JButton say;
    private javax.swing.JLabel sayisalderssayisi;
    private javax.swing.JButton soz;
    private javax.swing.JLabel sozelderssayisi;
    private javax.swing.JLabel toplamderssaati;
    // End of variables declaration//GEN-END:variables
}
